=== AS042971/bili-auto-note/schema/pub_timeline.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "轴发布配置文件",
  "description": "调用轴发布程序时提供的配置",
  "properties": {
    "cookie": {
      "description": "发送笔记用户的cookie",
      "type": "string"
    },
    "bvid": {
      "description": "目标视频BV号",
      "type": "string",
      "maxLength":12,
      "minLength":12
    },
    "timeline": {
      "description": "时间轴文件路径",
      "type": "string"
    },
    "offsets": {
      "description": "目标视频每个分P的开始时刻对应的统一时间轴时刻",
      "type": "array",
      "items": {
        "anyOf":[
          {
            "description": "分P开始时刻",
            "type": "integer"
          },
          {
            "description": "根据上一P开始时刻和时长自动推断分P开始时刻",
            "const": "auto"
          },
          {
            "description": "跳过这个分P",
            "const": "skip"
          }
        ]
      }
    },
    "danmakuOffsets": {
      "description": "目标视频每个弹幕版分P的开始时刻对应的统一时间轴时刻",
      "type": "array",
      "items": {
        "anyOf":[
          {
            "description": "分P开始时刻",
            "type": "integer"
          },
          {
            "description": "根据上一P开始时刻和时长自动推断分P开始时刻",
            "const": "auto"
          },
          {
            "description": "跳过这个分P",
            "const": "skip"
          }
        ]
      }
    },
    "ignoreThreshold": {
      "description": "时长短于此值的分P将被忽略，单位为秒",
      "type": "integer",
      "default": 600,
      "minimum": 0
    },
    "output": {
      "description": "文本轴输出路径",
      "type": "string"
    },
    "cover": {
      "description": "视频转制通过时发送至评论区的文案",
      "type": "string",
      "minLength": 1,
      "maxLength": 85
    },
    "preface": {
      "description": "笔记轴开头的文本",
      "type": "string",
      "maxLength": 1024
    },
    "prefaceNone": {
      "description": "没有正式发布笔记时，笔记轴开头的文本",
      "type": "string",
      "maxLength": 1024
    },
    "jumpOP": {
      "description": "是否生成跳过op的按钮",
      "type": "boolean"
    },
    "poem": {
      "description": "诗歌文件路径",
      "type": "string"
    },
    "songAndDanceAbstract": {
      "description": "是否生成歌舞摘要",
      "type": "boolean"
    },
    "publish": {
      "description": "是否自动发布",
      "type": "boolean"
    },
    "watch": {
      "description": "是否监控视频和笔记更新",
      "type": "boolean"
    },
    "confirm": {
      "description": "发布前是否确认",
      "type": "boolean"
    },
    "imgNode": {
      "description": "没有笔记的时候填充的图片",
      "type": "string",
      "maxLength": 1024
    }
  },
  "required": [
    "cookie",
    "bvid",
    "timeline",
    "offsets",
    "cover",
    "publish"
  ]
}

=== AS042971/bili-auto-note/example/config/pub_timeline.json
{
    "$schema": "../schema/pub_timeline.schema.json",
    "cookie": "SESSDATA=<SESSDATA>; bili_jct=<CSRF>",
    "bvid": "BV15U4y1d7TX",
    "timeline": "./data/timeline.csv",
    "offsets": [-52, "auto"],
    "danmakuOffsets": [-52, "auto"],
    "ignoreThreshold": 600,
    "output": "./data/output.txt",
    "cover": "这是一个多P自动发布笔记的测试\n欢迎进入笔记打轴的自动化时代",
    "preface": "【注意】今天也要开开心心地看录播",
    "songAndDanceAbstract": true,
    "publish": false,
    "watch": false
}
